import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AsendKit",
  description: "Generated by edoaditama",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
    
      >
        {children}
      </body>
    </html>
  );
}
